/**
 * Client-side generation of the per-record Verification Report PDF.
 * Uses jsPDF + autoTable so the download happens immediately in the browser
 * (no print dialog, no server round-trip).
 */
import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";

import type { AuditEvent } from "./audit";
import { AUDIT_LABELS } from "./audit";
import type { LandRecord, OfficerDecision } from "./pipeline/types";

const NAVY: [number, number, number] = [11, 60, 122];
const LIGHT: [number, number, number] = [235, 241, 249];

function dash(value: unknown): string {
  if (value === null || value === undefined || value === "") return "Not available";
  return String(value);
}

function shortId(id: string): string {
  return id.replace(/-/g, "").slice(0, 8).toUpperCase();
}

function riskLabel(score: number): string {
  if (score >= 60) return "HIGH RISK";
  if (score >= 30) return "MEDIUM RISK";
  return "LOW RISK";
}

function confidenceLabel(value: number): string {
  if (value >= 90) return "High Confidence";
  if (value >= 70) return "Medium Confidence";
  return "Low Confidence";
}

export function generateVerificationReport(options: {
  record: LandRecord;
  decisions: OfficerDecision[];
  events: AuditEvent[];
  related?: LandRecord[];
}): string {
  const { record, decisions, events, related = [] } = options;
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const pageWidth = doc.internal.pageSize.getWidth();

  // ---- Header -------------------------------------------------------------
  doc.setFillColor(...NAVY);
  doc.rect(0, 0, pageWidth, 74, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(17);
  doc.text("Land Record AI", 40, 32);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.text("Intelligent Land Record Digitization & Validation Portal", 40, 48);
  doc.setFontSize(9);
  doc.text("Verification Report", pageWidth - 40, 32, { align: "right" });
  doc.text(new Date().toLocaleString(), pageWidth - 40, 48, { align: "right" });

  doc.setTextColor(30, 30, 30);
  let y = 96;

  const section = (title: string) => {
    doc.setFont("helvetica", "bold");
    doc.setFontSize(11);
    doc.setTextColor(...NAVY);
    doc.text(title, 40, y);
    doc.setTextColor(30, 30, 30);
    y += 8;
  };

  const table = (head: string[], body: (string | number)[][]) => {
    autoTable(doc, {
      startY: y,
      head: [head],
      body: body.length > 0 ? body : [["No data recorded", ...head.slice(1).map(() => "—")]],
      theme: "grid",
      styles: { fontSize: 9, cellPadding: 5, textColor: [40, 40, 40] },
      headStyles: { fillColor: NAVY, textColor: [255, 255, 255], fontStyle: "bold" },
      alternateRowStyles: { fillColor: LIGHT },
      margin: { left: 40, right: 40 },
    });
    y = (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 24;
  };

  // ---- Report metadata ----------------------------------------------------
  section("Report Metadata");
  table(
    ["Field", "Value"],
    [
      ["Report reference", `LRAI-VR-${shortId(record.id)}`],
      ["Record ID", record.id],
      ["Record created", new Date(record.created_at).toLocaleString()],
      ["Source document", dash(record.document)],
      ["Generated on", new Date().toLocaleString()],
      ["Generated by", "Land Record AI portal (demo)"],
    ],
  );

  // ---- Extracted fields ---------------------------------------------------
  section("Extracted Land Record Fields");
  table(
    ["Field", "Extracted value"],
    [
      ["Owner Name", dash(record.owner)],
      ["Survey / Khasra Number", dash(record.survey_no)],
      ["Land Area (hectares)", record.area == null ? "Not available" : record.area.toFixed(2)],
      ["Village", dash(record.village)],
      ["Taluka / Tehsil", dash(record.taluka)],
      ["District", dash(record.district)],
      ["Land Type", dash(record.land_type)],
      ["Mutation Number", dash(record.mutation_no)],
      ["Registration Number", dash(record.registration_no)],
      [
        "Coordinates (demo/sample)",
        record.latitude == null || record.longitude == null
          ? "Not available"
          : `${record.latitude.toFixed(5)}, ${record.longitude.toFixed(5)}`,
      ],
    ],
  );

  // ---- Scores -------------------------------------------------------------
  const lastOf = (type: string) =>
    [...events].reverse().find((event) => event.event_type === type);
  const ocrEvent = lastOf("ocr");
  const extractionEvent = lastOf("extraction");
  const validationEvent = lastOf("validation");

  section("Confidence, Risk and AI Recommendation");
  table(
    ["Measure", "Value", "Interpretation"],
    [
      [
        "OCR confidence",
        ocrEvent?.confidence == null ? "Not available" : `${Math.round(ocrEvent.confidence)}%`,
        "Legibility of the scanned source document",
      ],
      [
        "Extraction confidence",
        extractionEvent?.confidence == null
          ? "Not available"
          : `${Math.round(extractionEvent.confidence)}%`,
        "Share of mandatory fields located by the rule-based extractor",
      ],
      [
        "Validation confidence",
        validationEvent?.confidence == null
          ? "Not available"
          : `${Math.round(validationEvent.confidence)}%`,
        "Internal consistency against the existing register",
      ],
      [
        "Overall confidence",
        `${Math.round(record.confidence)}%`,
        confidenceLabel(record.confidence),
      ],
      ["Anomaly risk score", `${Math.round(record.risk_score)}/100`, riskLabel(record.risk_score)],
      ["Processing status", dash(record.status), "Assigned automatically by the pipeline"],
      ["AI recommendation", dash(record.ai_recommendation), "Advisory only — never auto-approved"],
    ],
  );

  // ---- Officer decision ---------------------------------------------------
  const latest = decisions[0];
  section("Officer Verification");
  table(
    ["Field", "Value"],
    [
      ["Verification status", dash(record.verification_status)],
      ["Latest officer decision", dash(latest?.decision)],
      ["Deciding officer", dash(latest?.officer_name)],
      [
        "Decision timestamp",
        latest ? new Date(latest.created_at).toLocaleString() : "Not available",
      ],
      ["Officer notes", dash(latest?.notes)],
      ["Total decisions recorded", String(decisions.length)],
    ],
  );

  // ---- Explainable flags --------------------------------------------------
  section("Explainable Validation & Anomaly Breakdown");
  table(
    ["#", "Reason the record was flagged"],
    record.flags.length > 0
      ? record.flags.map((flag, index) => [String(index + 1), flag])
      : [["1", "No anomalies were detected for this record."]],
  );

  // ---- Comparison references ---------------------------------------------
  if (related.length > 0) {
    section("Comparison References (records sharing this survey number)");
    table(
      ["Record ID", "Owner", "Area (ha)", "Village", "Verification status"],
      related.map((other) => [
        shortId(other.id),
        dash(other.owner),
        other.area == null ? "—" : other.area.toFixed(2),
        dash(other.village),
        dash(other.verification_status),
      ]),
    );
  }

  // ---- Audit timeline -----------------------------------------------------
  section("Audit Timeline");
  table(
    ["Timestamp", "Stage", "Event", "Actor"],
    events.map((event) => [
      new Date(event.created_at).toLocaleString(),
      AUDIT_LABELS[event.event_type] ?? event.event_type,
      event.title,
      event.actor,
    ]),
  );

  // ---- Footer on every page ----------------------------------------------
  const pageCount = doc.getNumberOfPages();
  for (let page = 1; page <= pageCount; page += 1) {
    doc.setPage(page);
    const height = doc.internal.pageSize.getHeight();
    doc.setDrawColor(...NAVY);
    doc.line(40, height - 42, pageWidth - 40, height - 42);
    doc.setFontSize(8);
    doc.setTextColor(110, 110, 110);
    doc.text(
      "Land Record AI — prototype verification report. Sample/demo data; not a legal land title document.",
      40,
      height - 28,
    );
    doc.text(`Page ${page} of ${pageCount}`, pageWidth - 40, height - 28, { align: "right" });
  }

  const filename = `Land_Record_Verification_Report_${shortId(record.id)}.pdf`;
  doc.save(filename);
  return filename;
}
